services:
  _defaults:
    autowire: true
    autoconfigure: true

  WechatMiniProgramExpressBundle\Controller\:
    resource: '../../Controller/'
    public: true
    tags: ['controller.service_arguments']

  WechatMiniProgramExpressBundle\Service\:
    resource: '../../Service/'

  WechatMiniProgramExpressBundle\Repository\:
    resource: '../../Repository/'
    public: true

  WechatMiniProgramExpressBundle\Command\:
    resource: '../../Command/'