services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  WechatMiniProgramExpressBundle\DataFixtures\:
    resource: '../../DataFixtures'
    tags: ['doctrine.fixture.orm']